Repository so-sim/front, pull requests merged in 2023-06, with the labels that each got.

#95 Fix: home ui 카드와 footer가 겹치는 현상 수정
  src/components/Home/GroupSection/index.tsx
  src/components/Home/GroupSection/styles.ts
  src/components/Home/Header/index.tsx
  src/components/Home/Header/styles.ts
  src/components/Home/Paragraph/index.tsx
  src/components/Home/Paragraph/styles.ts
Labels: bug

#98 Refactor: finebook modal 컴포넌트 create, update로 분리
  src/components/@common/Calendar/index.tsx
  src/components/@common/DropBox/CalendarDropBox/index.tsx
  src/components/@common/DropBox/index.tsx
  src/components/@common/MiniCalendar/index.tsx
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FineBookUpdateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/@common/Modal/FineBookModal/index.tsx
  src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
  src/components/@common/Modal/FineBookModal/styles.ts
  src/components/@common/Modal/FineBookModal/test/FineBookCreateModal.stories.tsx
  src/components/@common/Modal/FineBookModal/test/FineBookModal.stories.tsx
  src/components/@common/Modal/FineBookModal/test/FineBookUpdateModal.stories.tsx
  src/components/DetailFine/DateController/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/pages/FineBook/DetailFine/index.tsx
  src/utils/convertPriceFormat.ts
  src/utils/removeCommaFromPayment.ts
  src/utils/statusList.ts
  src/utils/validation.ts
Labels: 🛠️ refactoring

#97 Refactor: Detail 페이지 ConfirmModal 추상화 및 useConfirmModal 훅 생성
  src/App.tsx
  src/components/@common/Calendar/index.tsx
  src/components/@common/DropBox/CalendarDropBox/index.tsx
  src/components/@common/DropBox/index.tsx
  src/components/@common/MiniCalendar/index.tsx
  src/components/@common/Modal/ConfirmModal/index.tsx
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FineBookUpdateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/@common/Modal/FineBookModal/index.tsx
  src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
  src/components/@common/Modal/FineBookModal/styles.ts
  src/components/@common/Modal/FineBookModal/test/FineBookCreateModal.stories.tsx
  src/components/@common/Modal/FineBookModal/test/FineBookModal.stories.tsx
  src/components/@common/Modal/FineBookModal/test/FineBookUpdateModal.stories.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
  src/components/@common/Modal/GroupSettingModal/UserModal/index.tsx
  src/components/@common/Modal/UserConfigModal/index.tsx
  src/components/DetailFine/CircleButtonList/index.tsx
  src/components/DetailFine/DateController/index.tsx
  src/components/DetailFine/Pagination/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/components/Home/Header/UserConfig/index.tsx
  src/components/MemberManagement/MemberListItem/index.tsx
  src/components/Withdrawal/Reason/index.tsx
  src/constants/Payment.ts
  src/hooks/useConfirmModal.ts
  src/hooks/useModal.ts
  src/layouts/Group/components/Header/index.tsx
  src/pages/FineBook/DetailFine/index.tsx
  src/store/confirmModalState.ts
  src/utils/convertPriceFormat.ts
  src/utils/removeCommaFromPayment.ts
  src/utils/statusList.ts
  src/utils/validation.ts
Labels: 🛠️ refactoring

#111 Feat : api 변경으로 인한 모임, 상세내역 msw api 수정
  src/mocks/api/detailHandler.ts
  src/mocks/api/groupHandler.ts
  src/mocks/data/detailData.ts
  src/mocks/data/groupData.ts
  src/mocks/utils/getSearchParams.ts
Labels: enhancement

#112 Refactor: 상세내역 api 수정 관련 변수명 및 타입 수정
  src/api/Event/index.ts
  src/api/Group/index.ts
  src/api/index.ts
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FineBookUpdateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
  src/components/@common/Modal/FineBookModal/test/FineBookUpdateModal.stories.tsx
  src/components/DetailFine/CircleButtonList/index.tsx
  src/components/DetailFine/CircleButtonList/test/CircleButtonList.test.tsx
  src/components/DetailFine/CircleDropButton/index.tsx
  src/components/DetailFine/CircleDropButton/styles.ts
  src/components/DetailFine/CircleDropButton/test/CircleDropButton.test.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/components/DetailFine/DropDownWrapper/index.tsx
  src/components/DetailFine/TableHead/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/components/DetailFine/UserDetails/styles.ts
  src/components/DetailFine/UserDetails/test/UserDetails.stories.tsx
  src/constants/Detail.ts
  src/mocks/api/groupHandler.ts
  src/mocks/data/detailData.ts
  src/pages/FineBook/DetailFine/index.tsx
  src/pages/MemberManagement/index.tsx
  src/queries/Auth/useUserWithdrawalMutation.ts
  src/queries/Detail/useUpdateDetail.ts
  src/queries/Detail/useUpdateDetailStatus.ts
  src/queries/Group/useChangeAdmin.ts
  src/queries/Group/useGroupList.ts
  src/types/event.d.ts
  src/types/group.d.ts
  src/utils/pushDataLayer.ts
  src/utils/status.ts
  src/utils/statusList.ts
  src/utils/validation.ts
Labels: 🛠️ refactoring

#113 DetailFine 에러 수정 네이밍 변경
  src/api/Event/index.ts
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FineBookUpdateModal/index.tsx
  src/components/DetailFine/DateController/index.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/components/DetailFine/Pagination/index.tsx
  src/components/DetailFine/TableHead/index.tsx
  src/pages/FineBook/DetailFine/index.tsx
  src/pages/WholeCalendar/index.tsx
  src/queries/Detail/useGetDetailList.ts
  src/utils/detailFilterToQuery.ts
  src/utils/tests/dateFilter.test.ts
Labels: enhancement

#114 Refactor: Calendar api 수정 및 UI 버그 수정
  src/api/Event/index.ts
  src/components/@common/Calendar/DateCellWithMark/index.tsx
  src/components/@common/Calendar/DateCellWithMark/styles.ts
  src/components/@common/Calendar/DateCellWithTag/index.tsx
  src/components/@common/Calendar/index.tsx
  src/components/@common/Calendar/styles.ts
  src/components/DetailFine/TableHead/index.tsx
  src/queries/Detail/useGetMonthStatus.ts
  src/types/event.d.ts
  src/utils/handleDate.ts
Labels: bug, 🛠️ refactoring

#115 dateStateTest -> dateState 네이밍 변경 및 그 외 네이밍 변경
  src/components/@common/Calendar/index.tsx
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FineBookUpdateModal/index.tsx
  src/components/DetailFine/DateController/hook/useDateController.ts
  src/components/DetailFine/DateController/hook/useFilter.ts
  src/components/DetailFine/DateController/index.tsx
  src/components/DetailFine/DateController/test/index.test.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/pages/FineBook/DetailFine/index.tsx
  src/pages/FineBook/DetailFine/test/DetailFine.test.tsx
  src/pages/WholeCalendar/index.tsx
  src/queries/Detail/useGetDetailList.ts
  src/store/dateState.ts
  src/store/dateStateTest.ts
  src/utils/dateFilter/dateFilter.ts
  src/utils/dateFilter/dayFilter.ts
  src/utils/dateFilter/monthFilter.ts
  src/utils/dateFilter/rootDateFilter.ts
  src/utils/dateFilter/weekFilter.ts
  src/utils/tests/dateFilter.test.ts
Labels: 🛠️ refactoring

#117 Refactor: 납부 여부 상태 변경 리팩터링 및 api 수정
  src/api/Event/index.ts
  src/components/DetailFine/CircleButtonList/index.tsx
  src/components/DetailFine/DropDownWrapper/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/hooks/useRecentlyVisitedGroup.ts
  src/pages/Home/index.tsx
  src/pages/Invitation/index.tsx
  src/pages/WholeCalendar/index.tsx
  src/utils/recentlyVisitedGroup.ts
Labels: bug, 🛠️ refactoring

#118 docs: 개발 서버 추가로 github actions workflow 업데이트
  .github/workflows/aws-deploy.yml
  .github/workflows/staging-aws-deploy.yml
  src/api/index.ts
Labels: documentation

#123 Feat: 납부 여부 상태 버튼명 어드민, 유저 분기 처리 및 스타일 수정
  .vscode/settings.json
  src/api/Auth/index.ts
  src/assets/icons/Arrow/Down.svg
  src/assets/icons/Arrow/index.tsx
  src/components/@common/Calendar/index.tsx
  src/components/@common/DropBox/CalendarDropBox/index.tsx
  src/components/@common/DropBox/index.tsx
  src/components/@common/DropBox/styles.ts
  src/components/@common/Modal/CreateGroupModal/index.tsx
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/DetailFine/CircleDropButton/test/CircleDropButton.test.tsx
  src/components/DetailFine/DateController/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleButtonList/styles.ts
  src/components/DetailFine/DropDownWrapper/CircleButtonList/test/CircleButtonList.test.tsx
  src/components/DetailFine/DropDownWrapper/CircleDropButton/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleDropButton/styles.ts
  src/components/DetailFine/DropDownWrapper/CircleDropButton/test/CircleDropButton.test.tsx
  src/components/DetailFine/DropDownWrapper/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/components/DetailFine/UserDetails/styles.ts
  src/components/DetailFine/index.tsx
  src/components/MemberManagement/MemberListItem/index.tsx
  src/hooks/useSituationList.ts
  src/layouts/Group/components/SideBar/index.tsx
  src/pages/MemberManagement/index.tsx
  src/pages/WholeCalendar/index.tsx
  src/queries/Group/useGroupDetail.ts
  src/store/userState.ts
Labels: enhancement

#124 사유 추가 기능 작업 및 그에 따른 UI 수정
  src/components/@common/Modal/FineBookModal/FineBookUpdateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/CircleCheckBox/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/CircleCheckBox/styles.ts
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
  src/components/@common/Modal/FineBookModal/styles.ts
  src/components/@common/Modal/FineBookModal/test/FineBookUpdateModal.stories.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/components/DetailFine/UserDetails/test/UserDetails.stories.tsx
  src/contexts/SelectedFineContext.tsx
  src/pages/FineBook/DetailFine/index.tsx
  src/queries/Detail/useGetDetailList.ts
Labels: enhancement, 🛠️ refactoring

#129 내역 추가(수정) 모달 기능 추가 및 버그 수정
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
Labels: enhancement, 🛠️ refactoring

#130 Fix: FineBookUpdate 오류 수정
  src/components/@common/Modal/FineBookModal/FineBookUpdateModal/index.tsx
Labels: bug

#136 feat: gtm dataLayer 코드 추가
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/queries/Detail/useGetDetailList.ts
  src/store/detailFilter.ts
Labels: documentation
