Repository so-sim/front, pull requests merged in 2023-07, with the labels that each got.

#138 오픈베타 에러 수정
  src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
  src/components/@common/Modal/GroupSettingModal/UserModal/index.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/components/DetailFine/DetailList/styles.ts
  src/components/DetailFine/UserDetails/index.tsx
  src/utils/convertPriceFormat.ts
  src/utils/customedWeek.ts
Labels: 🛠️ refactoring

#137 Fix: 닉네임에 이모지 포함되지 않도록 변경 및 버그 수정
  src/components/@common/Input/index.tsx
  src/utils/validation.ts
Labels: bug, enhancement

#139 Fix : 오픈 베타 오류 수정
  src/components/@common/GroupColorList/index.tsx
  src/components/@common/GroupColorList/styles.ts
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
  src/components/DetailFine/DateController/hook/useDateController.ts
  src/components/DetailFine/UserDetails/index.tsx
  src/utils/customedWeek.ts
Labels: bug, help wanted

#142 오픈 베타 핫픽스 수정
  src/components/@common/DropBox/CalendarDropBox/index.tsx
  src/components/@common/DropBox/styles.ts
  src/components/DetailFine/DateController/styles.ts
  src/components/DetailFine/UserDetails/index.tsx
  src/layouts/Group/components/SideBar/styles.ts
Labels: 🛠️ refactoring

#144 Hotfix: button naming 수정
  src/components/@common/Calendar/DateCellWithTag/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleDropButton/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleDropButton/test/CircleDropButton.test.tsx
  src/components/DetailFine/DropDownWrapper/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/hooks/useSituationList.ts
  src/queries/Auth/useUserWithdrawalMutation.ts
Labels: enhancement

#145 Hotfix: 버튼 네이밍 수정
  src/components/@common/Calendar/DateCellWithTag/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleDropButton/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleDropButton/test/CircleDropButton.test.tsx
  src/components/DetailFine/DropDownWrapper/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/hooks/useSituationList.ts
  src/queries/Auth/useUserWithdrawalMutation.ts
Labels: bug

#146 fix: button Text 변경 (situation)
  src/components/DetailFine/UserDetails/index.tsx
Labels: enhancement

#147 hotfix: button Text 변경 (situation)
  src/components/DetailFine/UserDetails/index.tsx
Labels: enhancement

#151 Feat: CustomFilter 로직 작성 및 2차 배포 필터링 기능 구현
  src/App.tsx
  src/api/Group/index.ts
  src/assets/icons/System/Close.svg
  src/assets/icons/System/Search.svg
  src/assets/icons/System/index.tsx
  src/assets/icons/User/index.tsx
  src/components/@common/Calendar/DateCellWithMark/index.tsx
  src/components/@common/Calendar/DateCellWithMark/styles.ts
  src/components/@common/DropBox/CalendarDropBox/index.tsx
  src/components/@common/GroupColorList/index.tsx
  src/components/@common/GroupColorList/styles.ts
  src/components/@common/Input/index.tsx
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
  src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
  src/components/@common/Modal/GroupSettingModal/UserModal/index.tsx
  src/components/@common/Modal/index.tsx
  src/components/DetailFine/DateController/FilterButton/index.tsx
  src/components/DetailFine/DateController/FilterButton/styles.ts
  src/components/DetailFine/DateController/PeriodSettingModal/PeriodInput/index.tsx
  src/components/DetailFine/DateController/PeriodSettingModal/PeriodInput/styles.ts
  src/components/DetailFine/DateController/PeriodSettingModal/index.tsx
  src/components/DetailFine/DateController/PeriodSettingModal/styles.ts
  src/components/DetailFine/DateController/PeriodSettingModal/test/PeriodSettingModal.stories.tsx
  src/components/DetailFine/DateController/hook/CustomFilter.ts
  src/components/DetailFine/DateController/hook/DateFilter.test.ts
  src/components/DetailFine/DateController/hook/DateFilter.ts
  src/components/DetailFine/DateController/hook/DayFilter.ts
  src/components/DetailFine/DateController/hook/MonthFilter.ts
  src/components/DetailFine/DateController/hook/WeekFilter.ts
  src/components/DetailFine/DateController/hook/useDateController.ts
  src/components/DetailFine/DateController/hook/useDateFilter.ts
  src/components/DetailFine/DateController/index.tsx
  src/components/DetailFine/DateController/styles.ts
  src/components/DetailFine/DetailList/index.tsx
  src/components/DetailFine/DetailList/styles.ts
  src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
  src/components/DetailFine/FilterController/AutoComplete/index.tsx
  src/components/DetailFine/FilterController/AutoComplete/styles.ts
  src/components/DetailFine/FilterController/index.tsx
  src/components/DetailFine/FilterController/styles.ts
  src/components/DetailFine/UserDetails/index.tsx
  src/components/DetailFine/index.tsx
  src/hooks/useDropDown.ts
  src/hooks/usePushUserId.ts
  src/pages/FineBook/DetailFine/index.tsx
  src/queries/Auth/useSignInQuery.ts
  src/queries/Detail/useGetDetailList.ts
  src/queries/Group/useSearchParticipantList.ts
  src/store/dateState.ts
  src/store/detailFilter.ts
  src/types/group.d.ts
  src/utils/convertPriceFormat.ts
  src/utils/customedWeek.ts
  src/utils/validation.ts
Labels: enhancement
