Repository so-sim/front, pull requests merged in 2023-08, with the labels that each got.

#153 Feat: 모임설정>알림설정 기능 완성 및 api 추가
  src/api/Group/index.ts
  src/components/@common/GroupColorList/index.tsx
  src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
  src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
  src/components/@common/Modal/GroupSettingModal/AdminModal/GroupForm/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/CommonForm/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/CommonForm/styles.ts
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/DaySelector/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/DaySelector/styles.ts
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/MonthForm/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/MonthForm/styles.ts
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/styles.ts
  src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/styles.ts
  src/components/@common/Modal/GroupSettingModal/AdminModal/utils/validation.ts
  src/components/@common/Tab/index.tsx
  src/components/@common/Tab/styles.ts
  src/components/@common/Toggle/index.tsx
  src/components/@common/Toggle/styles.ts
  src/components/DetailFine/FilterController/index.tsx
  src/queries/Group/index.ts
  src/queries/Group/useNotificationInfo.ts
  src/queries/Group/useUpdateNotificationInfo.ts
  src/styles/GlobalStyle.tsx
  src/types/group.d.ts
  src/utils/convertFormat.ts
  src/utils/convertPriceFormat.ts
Labels: enhancement

#150 납부 요청 및 납부 변경 페이지 작성 (checkBox는 임시로 생성)
  src/api/Notification/index.ts
  src/assets/icons/Arrow/index.tsx
  src/components/@common/Checkbox/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/CheckedFineList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/CheckedFineList/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/hooks/useCheckDetailFine.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/test/index.test.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/test/useCheckDetailFine.test.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/components/DetailFine/DetailList/styles.ts
  src/components/DetailFine/TableHead/CheckedHandleModal.tsx
  src/components/DetailFine/TableHead/index.tsx
  src/components/DetailFine/TableHead/styles.ts
  src/components/DetailFine/checkbox.tsx
  src/hooks/useMultiRefs.ts
  src/hooks/useOutSideClick.ts
  src/pages/FineBook/DetailFine/index.tsx
  src/pages/FineBook/DetailFine/styles.ts
  src/queries/Notification/useRequestNotifaction.ts
  src/store/sideModalState.ts
  src/styles/Theme.ts
Labels: enhancement

#156 Feat: 팀원검색>키보드 조작할 수 있도록 기능 추가
  src/assets/icons/System/Search.svg
  src/assets/icons/System/index.tsx
  src/components/DetailFine/FilterController/AutoComplete/index.tsx
  src/components/DetailFine/FilterController/AutoComplete/styles.ts
Labels: enhancement

#166 Feat: 알람 UI 및 알람 Response 리코일 설정
  src/api/Notification/index.ts
  src/assets/icons/Alarm/Alarm.svg
  src/assets/icons/Alarm/EmptyAlarm.svg
  src/assets/icons/Alarm/index.tsx
  src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
  src/components/Alarm/AlarmDetail/AlarmInfo/styles.ts
  src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/index.tsx
  src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/styles.ts
  src/components/Alarm/AlarmDetail/AlarmList/index.tsx
  src/components/Alarm/AlarmDetail/AlarmList/styles.ts
  src/components/Alarm/AlarmDetail/index.tsx
  src/components/Alarm/AlarmDetail/styles.ts
  src/components/Alarm/index.tsx
  src/components/Alarm/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/CheckedFineList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/hooks/useCheckDetailFine.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/styles.ts
  src/components/Home/Header/UserConfig/index.tsx
  src/components/Home/Header/UserConfig/style.ts
  src/components/Home/Header/index.tsx
  src/constants/Menu.ts
  src/layouts/Group/components/Header/index.tsx
  src/layouts/Group/components/Header/styles.ts
  src/queries/Notification/useGetAlarmList.ts
  src/store/alarmInfoState.ts
  src/types/notification.d.ts
Labels: enhancement

#167 Feat: mobile 라우터 셋팅
  src/App.tsx
  src/assets/icons/Logo/index.tsx
  src/assets/icons/System/Menu.svg
  src/assets/icons/System/index.tsx
  src/components/@common/Modal/styles.ts
  src/components/Home/Card/AddCard/index.tsx
  src/components/Home/Card/GroupCard/index.tsx
  src/components/Home/Card/GroupCard/styles.ts
  src/components/Home/Card/index.tsx
  src/components/Home/Card/styles.ts
  src/components/Home/CardList/index.tsx
  src/components/Home/CardList/styles.ts
  src/components/Home/Header/index.tsx
  src/constants/ServiceLink.ts
  src/hooks/Group/useInfinityGroupList.ts
  src/layouts/Mobile/components/MobileHeader/index.tsx
  src/layouts/Mobile/components/MobileHeader/styles.ts
  src/layouts/Mobile/components/MobileSideBar/index.tsx
  src/layouts/Mobile/components/MobileSideBar/styles.ts
  src/layouts/Mobile/index.tsx
  src/layouts/Mobile/styles.ts
  src/m-components/MobileHome/GroupSection/index.tsx
  src/m-components/MobileHome/GroupSection/styles.ts
  src/m-pages/MobileCreateGroup/index.tsx
  src/m-pages/MobileGroupHome/index.tsx
  src/m-pages/MobileHome/index.tsx
  src/routes/MobileRouter.tsx
  src/types/group.d.ts
Labels: enhancement

#176 모바일 상세내역 추가 및 CheckList(체크된 상세내역) 관리 리팩토링
  src/api/Event/index.ts
  src/assets/icons/System/MobileCon.svg
  src/assets/icons/System/MobileFull.svg
  src/assets/icons/System/MobileNon.svg
  src/assets/icons/System/index.tsx
  src/components/@common/Checkbox/SelectAllCheckbox/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/CheckedFineList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/hooks/useCheckSet.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/components/DetailFine/FilterController/index.tsx
  src/components/DetailFine/FilterController/styles.ts
  src/components/DetailFine/TableHead/index.tsx
  src/components/DetailFine/TableHead/styles.ts
  src/components/DetailFine/Toolbar/index.tsx
  src/components/DetailFine/Toolbar/styles.ts
  src/hooks/useCheckListState.ts
  src/m-components/MobileCalendar/index.tsx
  src/m-components/MobileCalendar/styles.ts
  src/m-components/MobileDetailFine/MobileDetailFineList/index.tsx
  src/m-components/MobileDetailFine/index.tsx
  src/m-pages/MobileCalendar/index.tsx
  src/pages/FineBook/DetailFine/index.tsx
  src/queries/Detail/useGetDetailListById.ts
  src/queries/Detail/useGetMobileDetailList.ts
  src/store/checkListState.ts
  src/store/checkedListState.ts
Labels: enhancement

#180 Feat: 초대권 페이지 모바일 추가
  src/components/@common/Label/index.tsx
  src/components/@common/Label/styles.ts
  src/components/@common/Modal/InvitationModal/index.tsx
  src/components/@common/Modal/InvitationModal/styles.ts
  src/pages/Invitation/index.tsx
  src/queries/Group/useJoinGroup.ts
Labels: enhancement

#182 Feat: 상세 내역페이지, 납부여부 변경 및 납부요청 페이지 생성
  src/api/Event/index.ts
  src/components/@common/Label/index.tsx
  src/components/@common/Label/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/styles.ts
  src/m-components/BottomSheet/SituationBottomSheet/index.tsx
  src/m-components/BottomSheet/SituationBottomSheet/styles.ts
  src/m-components/MobileDetailFine/MobileDetailFineList/index.tsx
  src/m-components/MobileDetailFine/MobileToolbar/index.tsx
  src/m-components/MobileDetailFine/MobileToolbar/styles.ts
  src/m-components/MobileDetailFine/index.tsx
  src/m-pages/MobileAlarmRequest_Payment/index.tsx
  src/m-pages/MobileFineBookDetail/index.tsx
  src/m-pages/MobileFineBookDetail/styles.ts
  src/pages/FineBook/DetailFine/index.tsx
  src/routes/MobileRouter.tsx
  src/store/sideModalState.ts
Labels: enhancement

#183 Feat: device별 라우팅 처리, mobile 컴포넌트 생성, issue 수정
  src/components/@common/DropDown/styles.ts
  src/components/@common/Input/index.tsx
  src/components/@common/Modal/ConfirmModal/index.tsx
  src/components/@common/Modal/ConfirmModal/styels.ts
  src/components/@common/Modal/CreateGroupModal/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/GroupForm/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
  src/components/@common/Modal/index.tsx
  src/components/@common/Modal/styles.ts
  src/constants/Confirm.ts
  src/constants/Group.ts
  src/hooks/@common/useRedirectURL.ts
  src/hooks/@common/useWindowHeight.ts
  src/hooks/Group/useGroupForm.ts
  src/layouts/Group/components/GroupList/index.tsx
  src/layouts/Group/components/SideBar/index.tsx
  src/layouts/Mobile/MobileLayout.tsx
  src/layouts/Mobile/ModalPageLayout.tsx
  src/layouts/Mobile/styles.ts
  src/m-components/@common/Dropbox/index.tsx
  src/m-components/@common/Dropbox/styles.ts
  src/m-components/@common/Label/index.tsx
  src/m-components/@common/Label/styles.ts
  src/m-components/BottomSheet/styles.ts
  src/m-components/MobileGroupForm/index.tsx
  src/m-components/MobileGroupForm/styles.ts
  src/m-components/MobileHome/Footer/index.tsx
  src/m-components/MobileHome/Footer/styles.ts
  src/m-components/MobileHome/GroupSection/index.tsx
  src/m-components/MobileHome/GroupSection/styles.ts
  src/m-pages/MobileCalendar/styles.ts
  src/m-pages/MobileCreateGroup/index.tsx
  src/m-pages/MobileHome/index.tsx
  src/m-pages/MobileSetting/MobileGroupSetting.tsx
  src/m-pages/MobileSetting/MobileUserGroupSetting.tsx
  src/m-pages/MobileSetting/index.tsx
  src/m-pages/MobileSetting/styles.ts
  src/m-pages/MobileUserSetting/styles.ts
  src/queries/Group/useChangeNickname.ts
  src/queries/Group/useCreateGroup.ts
  src/routes/MobileRouter.tsx
  src/routes/Router.tsx
Labels: bug, enhancement

#184 Fix: Date 포맷 수정 YYYY.MM.DD --> YYYY-MM-DD
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/components/DetailFine/DateController/PeriodSettingModal/index.tsx
  src/contexts/SelectedFineContext.tsx
  src/hooks/Group/useNotificationForm.ts
  src/m-components/BottomSheet/FilterBottomSheet/index.tsx
  src/pages/FineBook/DetailFine/index.tsx
  src/queries/Detail/useGetDetailList.ts
  src/queries/Detail/useGetMobileDetailList.ts
  src/utils/dateFilter/dayFilter.ts
  src/utils/dateFilter/monthFilter.ts
  src/utils/dateFilter/weekFilter.ts
  src/utils/handleDate.ts
Labels: 🛠️ refactoring

#191 Feat: style 수정 및 notification description 보여주도록 수정
  src/components/@common/Calendar/index.tsx
  src/components/@common/Calendar/styles.ts
  src/components/@common/Checkbox/SelectAllCheckbox/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/DaySelector/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/MonthForm/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/styles.ts
  src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
  src/components/@common/Tab/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/styles.ts
  src/components/DetailFine/DateController/FilterButton/index.tsx
  src/components/DetailFine/DateController/PeriodSettingModal/index.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/components/DetailFine/DetailList/styles.ts
  src/components/DetailFine/FilterController/AutoComplete/index.tsx
  src/components/DetailFine/FilterController/index.tsx
  src/components/DetailFine/TableHead/styles.ts
  src/components/DetailFine/checkbox.tsx
  src/hooks/Group/useNotificationForm.ts
  src/layouts/Group/index.tsx
  src/layouts/Mobile/components/MobileHeader/index.tsx
  src/m-components/MobileDetailFine/MobileDetailFineList/index.tsx
  src/m-components/MobileDetailFine/MobileDetailFineList/styles.ts
  src/m-pages/MobileAlarmRequest_Payment/index.tsx
  src/m-pages/MobileCalendar/index.tsx
  src/m-pages/MobileFineBookDetail/index.tsx
  src/routes/MobileRouter.tsx
  src/routes/Router.tsx
  src/types/group.d.ts
  src/utils/convertFormat.ts
Labels: enhancement

#192 Feat: 데스크탑 알람 기능 추가
  src/api/Notification/index.ts
  src/components/@common/Tooltip/index.tsx
  src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
  src/components/Alarm/AlarmDetail/AlarmInfo/styles.ts
  src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/index.tsx
  src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/styles.ts
  src/components/Alarm/AlarmDetail/AlarmList/index.tsx
  src/components/Alarm/AlarmDetail/AlarmList/styles.ts
  src/components/Alarm/AlarmDetail/index.tsx
  src/components/Alarm/AlarmDetail/styles.ts
  src/components/Alarm/index.tsx
  src/components/Alarm/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/layouts/Group/components/SideBar/index.tsx
  src/queries/Notification/useGetAlarmList.ts
  src/queries/Notification/useGetAlarmListCount.ts
  src/queries/Notification/useReadAllNotification.ts
  src/queries/Notification/useReadNotification.ts
  src/store/alarmInfoState.ts
  src/types/notification.d.ts
Labels: enhancement

#193 Feat: 모바일 Notification 페이지 추가
  src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
  src/components/Alarm/AlarmDetail/AlarmInfo/styles.ts
  src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/index.tsx
  src/components/Alarm/AlarmDetail/AlarmList/styles.ts
  src/components/Alarm/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/styles.ts
  src/m-pages/MobileNotificationInfo/index.tsx
  src/m-pages/MobileNotificationList/index.tsx
  src/routes/MobileRouter.tsx
Labels: enhancement

#195 Feat : hover, check, disabled 상태 추가 및 각종 스타일 수정
  src/components/@common/CheckStatusListWrapper/index.tsx
  src/components/@common/CheckStatusListWrapper/styles.ts
  src/components/@common/Checkbox/index.tsx
  src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/CheckedFineList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/CheckedFineList/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/checkbox.tsx
  src/hooks/useDisabledList.ts
  src/pages/FineBook/DetailFine/index.tsx
  src/styles/Theme.ts
Labels: enhancement

#196 Fix : QA 내용수정
  src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
  src/components/Alarm/AlarmDetail/AlarmList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/styles.ts
  src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
  src/components/DetailFine/Toolbar/index.tsx
  src/components/DetailFine/Toolbar/styles.ts
  src/components/DetailFine/UserDetails/index.tsx
  src/constants/Confirm.ts
Labels: enhancement

#198 Fix : QA 수정
  src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
  src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/styles.ts
  src/components/Alarm/AlarmDetail/AlarmList/index.tsx
  src/components/Alarm/AlarmDetail/AlarmList/styles.ts
  src/components/Alarm/styles.ts
Labels: enhancement

#199 Fix : QA (알람 클릭 redirect, 필터링 적용, 각종 스타일 수정)
  src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
  src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/index.tsx
  src/components/Alarm/AlarmDetail/AlarmList/index.tsx
  src/components/Alarm/AlarmDetail/index.tsx
  src/components/Alarm/AlarmDetail/styles.ts
  src/components/Alarm/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/FilterController/index.tsx
  src/constants/Situation.ts
  src/hooks/useLockScroll.ts
  src/layouts/Group/components/GroupList/index.tsx
  src/m-components/BottomSheet/FilterBottomSheet/index.tsx
  src/m-components/MobileDetailFine/MobileToolbar/index.tsx
  src/m-components/MobileDetailFine/MobileToolbar/styles.ts
  src/m-components/MobileDetailFine/index.tsx
  src/m-pages/MobileNotificationList/index.tsx
  src/pages/FineBook/DetailFine/index.tsx
Labels: enhancement

#201 Fix: QA리스트 수정
  src/api/Notification/index.ts
  src/assets/icons/Alarm/Alarm.svg
  src/assets/icons/Alarm/index.tsx
  src/assets/icons/System/Done.svg
  src/assets/icons/System/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/MonthForm/index.tsx
  src/components/@common/Tooltip/index.tsx
  src/components/@common/WithdrawBadge/index.tsx
  src/components/@common/WithdrawBadge/styles.ts
  src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/components/DetailFine/DetailList/styles.ts
  src/components/DetailFine/FilterController/AutoComplete/index.tsx
  src/components/DetailFine/FilterController/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/components/DetailFine/UserDetails/styles.ts
  src/components/Withdrawal/Reason/index.tsx
  src/constants/Confirm.ts
  src/hooks/Group/useNotificationForm.ts
  src/layouts/Group/components/Header/index.tsx
  src/layouts/Group/components/Header/styles.ts
  src/layouts/Group/index.tsx
  src/layouts/Group/styles.ts
  src/layouts/Mobile/ModalPageLayout.tsx
  src/m-pages/MobileFineBookDetail/index.tsx
  src/m-pages/MobileFineBookDetail/styles.ts
  src/m-pages/MobileMemberSearch/index.tsx
  src/queries/Group/useWithdrawalParticipantList.ts
Labels: bug, enhancement

#203 Feat : 체크박스 해지 영역 설정 / 알람창 Style / 알람 클릭 시 Filter 유지
  src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
  src/components/Alarm/AlarmDetail/AlarmInfo/styles.ts
  src/components/Alarm/AlarmDetail/index.tsx
  src/components/Alarm/AlarmDetail/styles.ts
  src/components/Alarm/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/components/Home/Header/UserConfig/index.tsx
  src/layouts/Group/components/Header/index.tsx
  src/layouts/Group/components/SideBar/index.tsx
  src/m-pages/MobileNotificationInfo/index.tsx
  src/pages/FineBook/DetailFine/index.tsx
  src/store/notificationModalState.ts
Labels: enhancement

#207 FIx: 페이지 이동 시 Checkbox 해지되는 오류 수정 및 해지 영역 확장
  src/components/DetailFine/DateController/FilterButton/index.tsx
  src/components/DetailFine/DateController/index.tsx
  src/components/DetailFine/FilterController/index.tsx
  src/pages/FineBook/DetailFine/index.tsx
Labels: enhancement

#206 Feat : useLockScroll 수정
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/CommonForm/index.tsx
  src/hooks/useLockScroll.ts
  src/layouts/Mobile/MobileLayout.tsx
  src/m-components/MobileDetailFine/index.tsx
  src/m-components/MobileFineBookForm/index.tsx
  src/m-pages/MobileCalendar/index.tsx
  src/m-pages/MobileFineBookDetail/index.tsx
  src/store/lockScrollState.ts
Labels: enhancement

#209 Style : 납부여부 및 요청 페이지 스타일 수정
  src/components/Alarm/AlarmDetail/AlarmInfo/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/styles.ts
  src/pages/FineBook/DetailFine/index.tsx
Labels: enhancement

#210 Feat: 상세내역 리스트 스타일 수정 / Mobile 무한스크롤 에러 수정 및 날짜 sticky
  src/components/DetailFine/DropDownWrapper/CircleDropButton/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleDropButton/styles.ts
  src/components/DetailFine/DropDownWrapper/index.tsx
  src/components/DetailFine/FilterController/index.tsx
  src/components/DetailFine/FilterController/styles.ts
  src/components/DetailFine/TableHead/styles.ts
  src/components/DetailFine/Toolbar/index.tsx
  src/components/DetailFine/Toolbar/styles.ts
  src/m-components/MobileDetailFine/MobileDetailFineList/index.tsx
  src/m-components/MobileDetailFine/MobileDetailFineList/styles.ts
  src/m-components/MobileDetailFine/index.tsx
  src/pages/FineBook/DetailFine/styles.ts
Labels: enhancement

#211 Fix: QA리스트 수정
  src/components/@common/Calendar/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/MonthForm/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/index.tsx
  src/components/@common/Modal/GroupSettingModal/AdminModal/utils/sortNotificationInfo.ts
  src/components/@common/Toast/index.tsx
  src/components/@common/Toast/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
  src/components/DetailFine/DropDownWrapper/index.tsx
  src/components/DetailFine/UserDetails/index.tsx
  src/constants/Confirm.ts
  src/hooks/Group/useNotificationForm.ts
  src/layouts/Group/components/SideBar/index.tsx
  src/m-components/BottomSheet/FilterBottomSheet/index.tsx
  src/m-components/MobileMiniCalendar/index.tsx
  src/queries/Group/useChangeNickname.ts
  src/queries/Group/useGroupList.ts
  src/queries/Group/useUpdateNotificationInfo.ts
  src/queries/Group/useWithdrawalGroup.ts
  src/styles/GlobalStyle.tsx
Labels: bug, enhancement

#212 Feat: 일괄 납부여부 변경 페이지 탈퇴회원 리스트 및 뱃지 추가 / AlarmInfo persist 적용 등 수정
  src/components/DetailFine/AlarmRequest_PaymentUpdate/CheckedFineList/index.tsx
  src/components/DetailFine/AlarmRequest_PaymentUpdate/CheckedFineList/styles.ts
  src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
  src/components/DetailFine/DetailList/index.tsx
  src/m-pages/MobileFineBookDetail/index.tsx
  src/pages/Home/index.tsx
  src/queries/Group/useWithdrawalParticipantList.ts
  src/store/alarmInfoState.ts
Labels: enhancement

#213 Feat: 스타일 수정 및 계속 추가하기 이슈 해결
  src/components/@common/MiniCalendar/styles.ts
  src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
  src/layouts/Group/components/SideBar/index.tsx
  src/layouts/Group/components/SideBar/styles.ts
  src/m-components/BottomSheet/TimeBottomeSheet/index.tsx
  src/m-pages/MobileCalendar/index.tsx
Labels: enhancement
